### ISSUE TITLE
no module named ._pycld2

### ISSUE THREAD

**Issue by yasaswini1995** [aboSamoor/pycld2#3] opened 2016-03-25 09:08 UTC
this is the issue i got while running setup.py

**Comment by bubzebub** [comment] 2017-04-03 15:58
Same issue using python2.7 and 3.4 on RHEL/CENTOS 6

**Comment by TobiasJu** [comment] 2019-09-10 14:37
Hey guys i had the exact same issue.
The following solution worked for me:

Go to the site-packages folder, i use miniconda so mine is:
`~/miniconda3/envs/ml/lib/python3.7/site-packages/pycld2`

rename the 
`_pycld2.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so`
to
`_pycld2.so`
done.

Seems like he has forgotten to include a rename in the setup.

**Comment by bsolomon1124** [comment] 2019-10-08 14:35
This problem is described here:

> https://stackoverflow.com/q/58275530/7954504

With a small reproducible example package here:

> https://github.com/bsolomon1124/hello-c-extension

There are two solutions:

1. Use `pip install pycld2` rather than `python setup.py install`.
2. If you do really want to install locally, then you **must CD out of the project root** to any directory point above it.  This is because, as explained [here](https://stackoverflow.com/a/58275728/7954504), the presence of the package sitting in your current directory otherwise confuses Python into not finding the C extension module in site-packages/.

**Comment by bsolomon1124** [comment] 2019-10-09 02:00
Closing this but please let us know if the problem persists and we can reopen.

**Closed by bsolomon1124** 2019-10-09 02:00 UTC

**Comment by Mrodent** [comment] 2023-10-03 11:40
I have this problem.
OS: W10.

```
>>> import pycld2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Downloads\pycld2-master\pycld2\__init__.py", line 1, in <module>
    from ._pycld2 import (
ModuleNotFoundError: No module named 'pycld2._pycld2'
```

This is after I installed using `python setup.py install` (because `pip install` fouled up).

TobiasJu's suggestion does not work for me: there is no "_pycld2.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so" in that directory (or anything like it). As regards bsolomon1124's post, I can't see the relevance of that linked SO question, or of the "reproducible example package".
