### ISSUE TITLE
Failed building wheel for pycld2 on Windows

### ISSUE THREAD

**Issue by milanpatel** [aboSamoor/pycld2#12] opened 2018-08-11 03:03 UTC
OS: Windows 10
Python 3.6.6
Getting following error while installing pycld2 

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Icld2\internal -Icld2\public "-Ic:\program files\python36\include" "-Ic:\program files\python36\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpbindings\pycldmodule.cc /Fobuild\temp.win-amd64-3.6\Release\bindings\pycldmodule.obj -w -O2 -m64 -fPIC
  cl : Command line warning D9025 : overriding '/W3' with '/w'
  cl : Command line warning D9002 : ignoring unknown option '-m64'
  cl : Command line warning D9002 : ignoring unknown option '-fPIC'
  pycldmodule.cc
  bindings\pycldmodule.cc(16): fatal error C1083: Cannot open include file: 'strings.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pycld2

**Comment by bsolomon1124** [comment] 2019-10-08 14:48
This is fixed in https://github.com/aboSamoor/pycld2/pull/15/files which is as of now unmerged.

The issue is that `strings.h` is a [less universally present variant](https://stackoverflow.com/q/4291149/7954504) that should be replaced with `string.h`.

**Comment by bsolomon1124** [comment] 2019-10-09 02:06
Should be fixed via c5e84d6 and 94a589d; please let us know if this is still an issue and we can reopen. (Note that the dev version is not as of right now on PyPI.)

N.B.: Duplicate of issue #7.

**Closed by bsolomon1124** 2019-10-09 02:06 UTC
